name: Add dataset to a data catalog
description: Submit metadata for a dataset
title: "[Dataset] "
labels: ["catalog-intake"]

body:
  - type: input
    id: catalog_id
    attributes:
      label: Catalog ID
      placeholder: "german-node"
    validations:
      required: true

  - type: input
    id: dataset_title
    attributes:
      label: Dataset title
      placeholder: "Overload dataset"
    validations:
      required: true
